"""
Basic type stubs for requests library.
"""
from typing import Any, Optional, Dict, Union

class Response:
    status_code: int
    text: str
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, data: Any = None, json: Any = None, **kwargs: Any) -> Response: ...
def put(url: str, data: Any = None, json: Any = None, **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...